name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    if: ${{ github.event_name != 'push' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - uses: pnpm/action-setup@v3

      - uses: actions/setup-node@v4
        with:
          cache: pnpm

      - run: pnpm install

      - run: |
          pnpm -F react build
          pnpm -F react exec -- pnpm --silent bundle-size > bundle-size-main.json

      - uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          path: bundle-size-main.json

      - uses: actions/checkout@v4

      - run: pnpm install

      - uses: actions/download-artifact@v4

      - run: pnpm -F react build

      - run: pnpm -F react bundle-size compare artifact/bundle-size-main.json

  # chromatic:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0

  #     - uses: actions/setup-node@v4
  #       with:
  #         cache: pnpm

  #     - run: pnpm install

  #     - uses: chromaui/action@latest
  #       with:
  #         buildScriptName: build:storybook
  #         exitZeroOnChanges: true
  #         projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3

      - uses: actions/setup-node@v4
        with:
          cache: pnpm

      - run: pnpm install

      - run: |
          pnpm -F react build
          pnpm lint --no-fix
          pnpm test run
