name: Visual

on:
  pull_request:
    branches: [main]
    types: [labeled]
  push:
    branches: [main]

jobs:
  chromatic:
    if: ${{ github.event_name == 'push' || github.event.label.name == 'visual' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v3

      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version-file: .node-version

      - run: |
          pnpm install
          pnpm build

      - uses: chromaui/action@latest
        with:
          buildScriptName: build
          exitZeroOnChanges: true
          projectToken: chpt_1768d7812fc589a
          workingDir: apps/storybook
